var fitCurve = require('../lib/fitCurves');
var _ = require('lodash');

var expectedResult;
var actualResult;

var assertSame = function (a, b) {
    if (Math.abs(a - b) > 1.0e-6) {
        throw new Error(a + " isn't " + b);
    }
};

var verifyMatch = function(expectedResult, actualResult){
    console.log(expectedResult);
    console.log("VS");
    console.log(actualResult);
    console.log("------");
    expectedResult.forEach(function (expectedBezierCurve, i) {
        var actualBezierCurve = actualResult[i];
        _.zip(actualBezierCurve, expectedBezierCurve).forEach(function (pairs) {
            assertSame(pairs[0][0], pairs[1][0]);
            assertSame(pairs[0][1], pairs[1][1]);
        });
    });
};

// These ground truth results generated by Python version

expectedResult = [
    [[0, 0], [20.27317402, 20.27317402], [-1.24665147, 0], [20, 0]]
];
actualResult = fitCurve([[0, 0], [10, 10], [10, 0], [20, 0]], 50);
verifyMatch(expectedResult, actualResult);


expectedResult = [
    [[0, 0], [ 22.76142375,  22.76142375], [ 2.6429774,  7.3570226], [10,  0]],
    [[10,  0], [ 12.3570226,  -2.3570226], [ 16.66666667,   0], [20,  0]]
];
actualResult = fitCurve([[0, 0], [10, 10], [10, 0], [20, 0]], 1);
verifyMatch(expectedResult, actualResult);

console.log('OK');

