// Generated by CoffeeScript 1.9.3
(function() {
  var math, multiply, q, qprime, qprimeprime, subtract;

  math = require('mathjs');

  multiply = math.multiply;

  subtract = math.subtract;

  q = function(ctrlPoly, t) {
    return math.chain(multiply(Math.pow(1.0 - t, 3), ctrlPoly[0])).add(multiply(3 * Math.pow(1.0 - t, 2) * t, ctrlPoly[1])).add(multiply(3 * (1.0 - t) * Math.pow(t, 2), ctrlPoly[2])).add(multiply(Math.pow(t, 3), ctrlPoly[3])).done();
  };

  qprime = function(ctrlPoly, t) {
    return math.chain(multiply(3 * Math.pow(1.0 - t, 2), subtract(ctrlPoly[1], ctrlPoly[0]))).add(multiply(6 * (1.0 - t) * t, subtract(ctrlPoly[2], ctrlPoly[1]))).add(multiply(3 * Math.pow(t, 2), subtract(ctrlPoly[3], ctrlPoly[2]))).done();
  };

  qprimeprime = function(ctrlPoly, t) {
    return math.chain(multiply(6 * (1.0 - t), add(subtract(ctrlPoly[2], 2 * ctrlPoly[1]), ctrlPoly[0]))).add(multiply(6 * t, add(subtract(ctrlPoly[3], 2 * ctrlPoly[2]), ctrlPoly[1]))).done();
  };

  module.exports = {
    q: q,
    qprime: qprime,
    qprimeprime: qprimeprime
  };

}).call(this);
